# Helixis — local stack lifecycle.
#
# SCOPING NOTE, and it is the reason several targets look more verbose than a
# `docker system prune` would: this Docker host is shared with unrelated
# projects. Every destructive target below filters by the `helixis` compose
# project, the `helixis-*` image prefix, or the `openshell-helixis-*` sandbox
# container prefix. Nothing here runs an unfiltered prune, and nothing here
# touches a volume it did not create.
#
#   make e2e     preflight -> build -> up -> health   (the one you want)
#   make clean   remove this stack's containers/images/volumes, KEEP runs+wiki
#   make nuke    clean, then wipe runs/ and wiki/ to a cold start (backs up first)

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := help

# HELIXIS_ROOT must be the absolute HOST path: claw-init hands it to the gateway
# as a bind-mount source, and the host daemon — not the container — resolves it.
export HELIXIS_ROOT := $(shell pwd)

COMPOSE := docker compose
PROJECT := helixis
SANDBOX_IMAGE := helixis-nemoclaw:latest
BACKUP_DIR := backups

# Images built outside compose (see `build`), plus the ones compose builds.
HELIXIS_IMAGES := helixis-nemoclaw helixis-openshell-cli helixis-dashboard helixis-engine
STAMP := $(shell date +%Y%m%d-%H%M%S)

.PHONY: help preflight auth-secret build build-sandbox up down restart health logs ps \
        clean clean-sandboxes clean-gateway-state nuke backup e2e shell-engine test \
        deploy deploy-sync tunnel

help:
	@echo "helixis"
	@echo
	@echo "  setup"
	@echo "    make preflight      check host, .env, ports, images — changes nothing"
	@echo "    make auth-secret    generate the missing HELIXIS_DASHBOARD_AUTH_SECRET into .env"
	@echo "    make build          build all four images (incl. the sandbox image compose does NOT build)"
	@echo "    make e2e            preflight + build + up + health"
	@echo
	@echo "  run"
	@echo "    make up / down / restart / ps / health"
	@echo "    make logs [S=claw-init]"
	@echo
	@echo "  teardown  (all helixis-scoped — never touches other projects)"
	@echo "    make clean          containers + images + volumes; KEEPS runs/ and wiki/"
	@echo "    make nuke           clean + wipe runs/ and wiki/ (backs up to $(BACKUP_DIR)/ first)"
	@echo "    make backup         snapshot runs/ + wiki/ only"
	@echo
	@echo "  deploy  (single VPS; nothing is published publicly by default)"
	@echo "    make deploy H=user@host       provision + sync + build + up + verify"
	@echo "    make deploy-sync H=user@host  push code and restart, no rebuild"
	@echo "    make tunnel H=user@host       SSH-forward the remote ports to localhost"

# ---------------------------------------------------------------------------
# setup
# ---------------------------------------------------------------------------

preflight:
	@bash scripts/preflight.sh

# Compose maps HELIXIS_DASHBOARD_AUTH_SECRET -> AUTH_SECRET with no default.
# Measured on this image: with it empty, next-auth v5 still serves /login with a
# 200 and fails only on SUBMIT, logging `[auth][error] MissingSecret`. So the
# symptom is "correct password rejected", not an obvious config error.
# Appends rather than rewrites, and refuses to clobber an existing value
# (rotating it would invalidate every live session).
auth-secret:
	@if [ ! -f .env ]; then echo "no .env — run: cp .env.example .env"; exit 1; fi
	@if grep -qE '^HELIXIS_DASHBOARD_AUTH_SECRET=.+' .env; then \
	  echo "HELIXIS_DASHBOARD_AUTH_SECRET already set — leaving it alone"; \
	else \
	  sed -i.bak '/^HELIXIS_DASHBOARD_AUTH_SECRET=/d' .env && rm -f .env.bak; \
	  printf '\n# Signs the dashboard session JWTs. Generated by `make auth-secret`.\nHELIXIS_DASHBOARD_AUTH_SECRET=%s\n' \
	    "$$(openssl rand -base64 32)" >> .env; \
	  echo "wrote HELIXIS_DASHBOARD_AUTH_SECRET to .env"; \
	fi

# The sandbox image is built HERE and nowhere else. No compose service declares
# it — claw-init.sh only consumes it by tag (HELIXIS_SANDBOX_IMAGE) — so a fresh
# clone that runs plain `docker compose up` fails at sandbox creation with a
# missing-image error several minutes in. This target is what closes that gap.
build-sandbox:
	@echo ">> building $(SANDBOX_IMAGE) (not built by compose)"
	docker build -f docker/nemoclaw.Dockerfile -t $(SANDBOX_IMAGE) .

build: build-sandbox
	@echo ">> building compose-managed images"
	$(COMPOSE) build engine dashboard claw-init

# ---------------------------------------------------------------------------
# run
# ---------------------------------------------------------------------------

# claw-init is a one-shot; `up` waits for it so a provisioning failure surfaces
# here rather than as a mysteriously-down claw-forward later.
up:
	@if ! docker image inspect $(SANDBOX_IMAGE) >/dev/null 2>&1; then \
	  echo "$(SANDBOX_IMAGE) missing — run 'make build' first"; exit 1; fi
	$(COMPOSE) up -d openshell
	$(COMPOSE) up -d claw-sync
	$(COMPOSE) up --exit-code-from claw-init claw-init || \
	  { echo ">> claw-init failed; logs above"; exit 1; }
	$(COMPOSE) up -d claw-forward dashboard
	@echo ">> up. 'make health' to verify (allow ~30s for tunnels)."

down:
	$(COMPOSE) down --remove-orphans

restart: down up

ps:
	@$(COMPOSE) ps -a

health:
	@bash scripts/health.sh

logs:
	@$(COMPOSE) logs --tail=100 -f $(or $(S),)

shell-engine:
	$(COMPOSE) run --rm --entrypoint bash engine

test:
	$(COMPOSE) run --rm --entrypoint python engine -m pytest /app/app/engine/tests -q

e2e: preflight build up health

# ---------------------------------------------------------------------------
# teardown — every rm below is filtered; see the scoping note at the top
# ---------------------------------------------------------------------------

# Gateway-created sandboxes are siblings on the host daemon, NOT compose
# services, so `compose down` leaves them running. The name prefix is set by
# OpenShell (openshell-<sandbox>-<uuid>), which is what makes this safe to filter
# on: no other project's container can match it.
clean-sandboxes:
	@ids=$$(docker ps -aq --filter "name=^openshell-$(PROJECT)-" 2>/dev/null || true); \
	if [ -n "$$ids" ]; then echo ">> removing sandbox containers"; docker rm -f $$ids; \
	else echo ">> no sandbox containers"; fi

# The gateway's own state: JWT signing material + gateway.db (its sandbox
# records). Must go when the volumes go, or the gateway boots holding records
# for sandboxes whose volumes no longer exist.
#
# Deleted through a container because on Docker Desktop /var/lib/openshell lives
# inside the VM, not on the macOS host — `rm -rf` here would silently do nothing.
clean-gateway-state:
	@echo ">> clearing /var/lib/openshell (gateway JWT + db)"
	@docker run --rm -v /var/lib/openshell:/state alpine:3.20 \
	  sh -c 'rm -rf /state/* /state/.[!.]* 2>/dev/null; true'

clean: clean-sandboxes
	@echo ">> compose down (removes the helixis-wiki / helixis-claw-sessions volumes)"
	-$(COMPOSE) down -v --remove-orphans
	@$(MAKE) --no-print-directory clean-gateway-state
	@echo ">> removing helixis images"
	@for img in $(HELIXIS_IMAGES); do \
	  docker image rm -f $$img:latest >/dev/null 2>&1 && echo "   removed $$img:latest" || true; \
	done
	@echo ">> done. runs/ and wiki/ untouched — 'make nuke' wipes those too."
	@echo "   (other projects' containers, images and volumes were not touched)"

# ---------------------------------------------------------------------------
# deploy
# ---------------------------------------------------------------------------

.PHONY: _require_host
_require_host:
	@[ -n "$(H)" ] || { echo "set H=user@host, e.g. make deploy H=root@203.0.113.10"; exit 1; }

deploy: _require_host
	@bash deploy/deploy.sh $(H) $(FLAGS)

deploy-sync: _require_host
	@bash deploy/deploy.sh $(H) --sync-only

tunnel: _require_host
	@bash deploy/tunnel.sh $(H)

backup:
	@mkdir -p $(BACKUP_DIR)
	@tar czf $(BACKUP_DIR)/helixis-state-$(STAMP).tgz \
	  $$( [ -d runs ] && echo runs ) $$( [ -d wiki ] && echo wiki ) 2>/dev/null || true
	@echo ">> $(BACKUP_DIR)/helixis-state-$(STAMP).tgz"

# Cold start. Interactive confirmation is deliberate and is NOT belt-and-braces:
# runs/claw-sessions/ holds the only copy of every real agent conversation, and
# the runbook flags those as unredacted. A backup is taken regardless.
nuke: backup clean
	@echo
	@echo "About to DELETE runs/ and wiki/ — including runs/claw-sessions/,"
	@echo "the only copy of your real agent transcripts. Backup written above."
	@read -p "Type 'wipe' to confirm: " a; [ "$$a" = "wipe" ] || { echo "aborted"; exit 1; }
	rm -rf runs wiki
	mkdir -p runs/claw-sessions wiki/skills wiki/pages
	@echo ">> wiped to cold start."
